// lib/theme/app_colors.dart

import 'package:flutter/material.dart';
import 'app_theme_config.dart';

/// Все палитры приложения.
/// 8 цветов × 2 яркости = 16 AppPalette.
class AppColors {
  // ============================================================
  // СВЕТЛЫЕ ПАЛИТРЫ
  // ============================================================

  static final Map<String, AppPalette> lightPalettes = {
    'rose': const AppPalette(
      id: 'rose',
      name: 'Нежно-розовая',
      accent: Color(0xFFE8A0B5),
      accentSoft: Color(0xFFFDEEF3),
      accentDeep: Color(0xFFC77B91),
      background: Color(0xFFFFFFFF),
      card: Color(0xFFF9FAFB),
      cardElevated: Color(0xFFFFFFFF),
      text: Color(0xFF1F1F1F),
      textSecondary: Color(0xFF8E8E93),
      border: Color(0xFFF0EEF0),
      danger: Color(0xFFE5484D),
      success: Color(0xFF30A46C),
      warning: Color(0xFFF5A623),
      info: Color(0xFF5B5BD6),
    ),
    'wine': const AppPalette(
      id: 'wine',
      name: 'Винная',
      accent: Color(0xFF722F37),
      accentSoft: Color(0xFFF4E8EA),
      accentDeep: Color(0xFF4F1E24),
      background: Color(0xFFFDFBFA),
      card: Color(0xFFF7F2F1),
      cardElevated: Color(0xFFFFFFFF),
      text: Color(0xFF2A1A1C),
      textSecondary: Color(0xFF8C7A7C),
      border: Color(0xFFEBE0DF),
      danger: Color(0xFFD14545),
      success: Color(0xFF4A8B5E),
      warning: Color(0xFFC98A2F),
      info: Color(0xFF5F4B8B),
    ),
    'burgundy': const AppPalette(
      id: 'burgundy',
      name: 'Бордовая',
      accent: Color(0xFF8E2D3A),
      accentSoft: Color(0xFFF7E8EB),
      accentDeep: Color(0xFF5C1B24),
      background: Color(0xFFFFFFFF),
      card: Color(0xFFF8F5F5),
      cardElevated: Color(0xFFFFFFFF),
      text: Color(0xFF241518),
      textSecondary: Color(0xFF8A7A7D),
      border: Color(0xFFEFE4E5),
      danger: Color(0xFFD63B3B),
      success: Color(0xFF3F8A5C),
      warning: Color(0xFFD08A2E),
      info: Color(0xFF5C4A9E),
    ),
    'emerald': const AppPalette(
      id: 'emerald',
      name: 'Изумрудная',
      accent: Color(0xFF2E8B57),
      accentSoft: Color(0xFFE6F4EC),
      accentDeep: Color(0xFF1B5E3A),
      background: Color(0xFFFFFFFF),
      card: Color(0xFFF4F8F5),
      cardElevated: Color(0xFFFFFFFF),
      text: Color(0xFF16261D),
      textSecondary: Color(0xFF7A857E),
      border: Color(0xFFE2EDE6),
      danger: Color(0xFFD44444),
      success: Color(0xFF2E8B57),
      warning: Color(0xFFD08A2E),
      info: Color(0xFF3A6DA8),
    ),
    'forest': const AppPalette(
      id: 'forest',
      name: 'Лесная',
      accent: Color(0xFF3A5A40),
      accentSoft: Color(0xFFE9EFE9),
      accentDeep: Color(0xFF223624),
      background: Color(0xFFFCFDFB),
      card: Color(0xFFF3F6F2),
      cardElevated: Color(0xFFFFFFFF),
      text: Color(0xFF1B241C),
      textSecondary: Color(0xFF7E877E),
      border: Color(0xFFE5EBE4),
      danger: Color(0xFFC94242),
      success: Color(0xFF3F7E4B),
      warning: Color(0xFFC9892E),
      info: Color(0xFF4A5F8A),
    ),
    'sapphire': const AppPalette(
      id: 'sapphire',
      name: 'Сапфировая',
      accent: Color(0xFF2C5F8D),
      accentSoft: Color(0xFFE8F0F7),
      accentDeep: Color(0xFF1B3F60),
      background: Color(0xFFFFFFFF),
      card: Color(0xFFF4F7FA),
      cardElevated: Color(0xFFFFFFFF),
      text: Color(0xFF16212B),
      textSecondary: Color(0xFF7C858F),
      border: Color(0xFFE4EAF0),
      danger: Color(0xFFD24444),
      success: Color(0xFF3F8A5C),
      warning: Color(0xFFD08A2E),
      info: Color(0xFF2C5F8D),
    ),
    'sky': const AppPalette(
      id: 'sky',
      name: 'Небесная',
      accent: Color(0xFF6BB6E8),
      accentSoft: Color(0xFFEAF4FC),
      accentDeep: Color(0xFF3F86B8),
      background: Color(0xFFFFFFFF),
      card: Color(0xFFF5F9FC),
      cardElevated: Color(0xFFFFFFFF),
      text: Color(0xFF18242C),
      textSecondary: Color(0xFF7C8792),
      border: Color(0xFFE5EDF3),
      danger: Color(0xFFD24444),
      success: Color(0xFF3F8A5C),
      warning: Color(0xFFD08A2E),
      info: Color(0xFF6BB6E8),
    ),
    'crimson': const AppPalette(
      id: 'crimson',
      name: 'Карминная',
      accent: Color(0xFFB83A4B),
      accentSoft: Color(0xFFFBE8EB),
      accentDeep: Color(0xFF7A1F2C),
      background: Color(0xFFFFFFFF),
      card: Color(0xFFF9F4F4),
      cardElevated: Color(0xFFFFFFFF),
      text: Color(0xFF231518),
      textSecondary: Color(0xFF8A7B7D),
      border: Color(0xFFEFE2E4),
      danger: Color(0xFFD63B3B),
      success: Color(0xFF3F8A5C),
      warning: Color(0xFFD08A2E),
      info: Color(0xFF5C4A9E),
    ),
  };

  // ============================================================
  // ТЁМНЫЕ ПАЛИТРЫ
  // ============================================================

  static final Map<String, AppPalette> darkPalettes = {
    'rose': const AppPalette(
      id: 'rose',
      name: 'Нежно-розовая',
      accent: Color(0xFFF4B8C8),
      accentSoft: Color(0xFF3A2830),
      accentDeep: Color(0xFFE8A0B5),
      background: Color(0xFF0E0C0D),
      card: Color(0xFF1C1A1B),
      cardElevated: Color(0xFF242122),
      text: Color(0xFFF5F2F3),
      textSecondary: Color(0xFFA39A9C),
      border: Color(0xFF2C2829),
      danger: Color(0xFFFF6B6B),
      success: Color(0xFF52C41A),
      warning: Color(0xFFFFB020),
      info: Color(0xFF8E8EFF),
    ),
    'wine': const AppPalette(
      id: 'wine',
      name: 'Винная',
      accent: Color(0xFFA85260),
      accentSoft: Color(0xFF2E1F22),
      accentDeep: Color(0xFF722F37),
      background: Color(0xFF0D0A0B),
      card: Color(0xFF1B1617),
      cardElevated: Color(0xFF241D1F),
      text: Color(0xFFF2EDEE),
      textSecondary: Color(0xFF9B8E90),
      border: Color(0xFF2B2425),
      danger: Color(0xFFFF6B6B),
      success: Color(0xFF52C41A),
      warning: Color(0xFFFFB020),
      info: Color(0xFF8E8EFF),
    ),
    'burgundy': const AppPalette(
      id: 'burgundy',
      name: 'Бордовая',
      accent: Color(0xFFC24A5C),
      accentSoft: Color(0xFF331E22),
      accentDeep: Color(0xFF8E2D3A),
      background: Color(0xFF0D0909),
      card: Color(0xFF1B1415),
      cardElevated: Color(0xFF241B1D),
      text: Color(0xFFF3EDED),
      textSecondary: Color(0xFF9C8D8E),
      border: Color(0xFF2B2223),
      danger: Color(0xFFFF6B6B),
      success: Color(0xFF52C41A),
      warning: Color(0xFFFFB020),
      info: Color(0xFF8E8EFF),
    ),
    'emerald': const AppPalette(
      id: 'emerald',
      name: 'Изумрудная',
      accent: Color(0xFF4DB47C),
      accentSoft: Color(0xFF1B2E22),
      accentDeep: Color(0xFF2E8B57),
      background: Color(0xFF0A0D0B),
      card: Color(0xFF141A16),
      cardElevated: Color(0xFF1C241E),
      text: Color(0xFFEEF3EF),
      textSecondary: Color(0xFF8E998F),
      border: Color(0xFF212A23),
      danger: Color(0xFFFF6B6B),
      success: Color(0xFF4DB47C),
      warning: Color(0xFFFFB020),
      info: Color(0xFF8E8EFF),
    ),
    'forest': const AppPalette(
      id: 'forest',
      name: 'Лесная',
      accent: Color(0xFF5C8A63),
      accentSoft: Color(0xFF1A231B),
      accentDeep: Color(0xFF3A5A40),
      background: Color(0xFF0A0C0A),
      card: Color(0xFF141814),
      cardElevated: Color(0xFF1C221C),
      text: Color(0xFFEEF2EE),
      textSecondary: Color(0xFF8F998F),
      border: Color(0xFF212721),
      danger: Color(0xFFFF6B6B),
      success: Color(0xFF5C8A63),
      warning: Color(0xFFFFB020),
      info: Color(0xFF8E8EFF),
    ),
    'sapphire': const AppPalette(
      id: 'sapphire',
      name: 'Сапфировая',
      accent: Color(0xFF4F84B8),
      accentSoft: Color(0xFF1A2430),
      accentDeep: Color(0xFF2C5F8D),
      background: Color(0xFF090C0F),
      card: Color(0xFF131820),
      cardElevated: Color(0xFF1B222C),
      text: Color(0xFFEDF1F5),
      textSecondary: Color(0xFF8D96A0),
      border: Color(0xFF202730),
      danger: Color(0xFFFF6B6B),
      success: Color(0xFF52C41A),
      warning: Color(0xFFFFB020),
      info: Color(0xFF4F84B8),
    ),
    'sky': const AppPalette(
      id: 'sky',
      name: 'Небесная',
      accent: Color(0xFF8FCDF2),
      accentSoft: Color(0xFF1B2A35),
      accentDeep: Color(0xFF6BB6E8),
      background: Color(0xFF0A0D10),
      card: Color(0xFF141920),
      cardElevated: Color(0xFF1C232C),
      text: Color(0xFFEEF3F7),
      textSecondary: Color(0xFF8D97A1),
      border: Color(0xFF212830),
      danger: Color(0xFFFF6B6B),
      success: Color(0xFF52C41A),
      warning: Color(0xFFFFB020),
      info: Color(0xFF8FCDF2),
    ),
    'crimson': const AppPalette(
      id: 'crimson',
      name: 'Карминная',
      accent: Color(0xFFD8546A),
      accentSoft: Color(0xFF331A20),
      accentDeep: Color(0xFFB83A4B),
      background: Color(0xFF0E090A),
      card: Color(0xFF1C1314),
      cardElevated: Color(0xFF25191B),
      text: Color(0xFFF5EEEF),
      textSecondary: Color(0xFF9F8F91),
      border: Color(0xFF2C2224),
      danger: Color(0xFFFF6B6B),
      success: Color(0xFF52C41A),
      warning: Color(0xFFFFB020),
      info: Color(0xFF8E8EFF),
    ),
  };

  // ============================================================
  // ДЕФОЛТ
  // ============================================================

  static const String defaultPaletteId = 'rose';
  static const Brightness defaultBrightness = Brightness.light;

  /// Палитра по умолчанию (light + rose).
  static AppPalette get defaultPalette => lightPalettes[defaultPaletteId]!;
}